version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/testDB"
    networks:
      - foodlink-network

  mongo:
    build:
      context: .
      dockerfile: docker/mongo/Dockerfile
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "foodlink" 
    networks:
      - foodlink-network

volumes:
  mongo-data:
    driver: local

networks:
  foodlink-network:
    driver: bridge
