homepage: https://github.com/CodeIntelligenceTesting/jazzer.js
language: javascript
main_repo: https://github.com/CodeIntelligenceTesting/jazzer.js
fuzzing_engines:
  - libfuzzer
sanitizers:
  - none
