name: CI/CD Pipeline for FoodLink API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        npm-version: '7.x'

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Unit Tests with Coverage
      run: npm run test -- --coverage --testPathIgnorePatterns='<rootDir>/test/models/' '<rootDir>/test/integrations/' '<rootDir>/test/routes/analyticsRoutes.test.ts' '<rootDir>/test/gateway/gateway.test.ts' '<rootDir>/test/routes/logisticsRoutes.test.ts' '<rootDir>/test/controllers/logisticsController.test.ts' '<rootDir>/test/services/logisticsService.test.ts' '<rootDir>/test/utils/googleMaps.test.ts',

    - name: Upload Coverage as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./coverage/lcov.info

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3