name: CI/CD Pipeline for FoodLink API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        npm-version: '7.x'

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Unit Tests with Coverage
      run: npm run test -- --coverage

    - name: Upload Coverage as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./coverage/lcov.info

    - name: Run SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
